/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ai.yinyang_solver;

public class App {
    public static void main(String[] args) {
        char[][] initialBoard = {
            {'0', '0', '0', 'B', '0', 'W'},
            {'0', '0', 'B', '0', 'B', '0'},
            {'0', '0', 'W', '0', '0', '0'},
            {'B', '0', '0', '0', 'W', '0'},
            {'0', 'B', '0', 'B', '0', '0'},
            {'W', '0', '0', '0', '0', '0'}
        };

        // Gunakan seed spesifik untuk hasil yang konsisten
        long seed = 12345L;
        YinYangSolver solver = new YinYangSolver(initialBoard, seed);
        
        System.out.println("Initial Board:");
        System.out.println(new YinYangBoard(initialBoard).toString());
        
        System.out.println("\nSolving with seed: " + solver.getSeed());
        YinYangBoard solution = solver.solve();
        
        System.out.println("\nFinal Solution:");
        System.out.println(solution.toString());
    }
}
