/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ai.yinyang_solver;

public class App {
    public static void main(String[] args) {
        // Example board
        char[][] board = {
            {'0', '0', '0', '0', '0', '0'},
            {'0', '0', 'B', '0', '0', '0'},
            {'0', 'W', '0', 'B', 'W', '0'},
            {'0', 'W', 'W', 'W', '0', '0'},
            {'0', 'W', '0', '0', 'W', '0'},
            {'0', '0', 'B', '0', '0', 'B'},
        };

        // Try different population sizes
        int[] populationSizes = {1000, 2000, 5000, 10000};
        
        for (int popSize : populationSizes) {
            System.out.println("\nTesting with population size: " + popSize);
            YinYangSolver solver = new YinYangSolver(board, popSize);
            solver.solve();
        }

        // Generate comparison plot
        YinYangSolver.plotAllFitnessHistories();
        System.out.println("\nFitness history comparison plot has been saved as 'fitness_history_comparison.png'");
    }
}
